/*
 * CONFIG_SECONDARY_BOOT_SECTOR_OFFSET was intended to be used as a compile time setting.
 * If CONFIG_SECONDARY_BOOT_RUNTIME_DETECTION is defined, then only use the base offset of 0x300 here.
 * CONFIG_SECONDARY_BOOT_SECTOR_OFFSET will be added dynamically if needed.
 */
#ifndef CONFIG_SECONDARY_BOOT_RUNTIME_DETECTION
#undef CONFIG_SYS_MMCSD_RAW_MODE_U_BOOT_SECTOR
#define CONFIG_SYS_MMCSD_RAW_MODE_U_BOOT_SECTOR	(0x300 + CONFIG_SECONDARY_BOOT_SECTOR_OFFSET)
#endif /* CONFIG_SECONDARY_BOOT_RUNTIME_DETECTION */

